### ISSUE TITLE
Bug : Introduction Word on Mobile View

### ISSUE THREAD

**Issue by TartejBrothers** [pippim/pippim.github.io#2]
There are 2 problems with the introduction header
1. The word doesn't fit in a single line in the mobile view 
![image](https://github.com/pippim/pippim.github.io/assets/112921727/4aefe54e-463f-4381-81f2-34bbb009e55d)
2. The word is covered up by a logo when skip is clicked.
![image](https://github.com/pippim/pippim.github.io/assets/112921727/c80f2389-2926-492d-bbd8-94534bf29c7f)

**Comment by pippim** [comment]
#1 has been fixed.

#2 isn't really broken because the lightning bolt automatically appears during scrolling and fades out a few seconds after scrolling stops.

Thank you for reporting mobile issues.

**Comment by TartejBrothers** [comment]
Ok cool.
